# Generated by Django 6.0.4 on 2026-04-20 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaMenor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tramite', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_gastado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_restante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCajaMenor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_factura', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=50)),
                ('pagado_a', models.CharField(max_length=150)),
                ('concepto', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cajamenor')),
            ],
        ),
    ]
