# Generated by Django 6.0.4 on 2026-04-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajamenor',
            name='total_gastado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cajamenor',
            name='valor_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
