# Generated by Django 6.0.4 on 2026-04-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cajamenor_total_gastado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaJuntaDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(max_length=20, unique=True)),
                ('nombre_entidad', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('presidente', models.CharField(max_length=150)),
                ('secretario', models.CharField(max_length=150)),
                ('orden_del_dia', models.TextField()),
                ('desarrollo', models.TextField()),
                ('proposiciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
