# Generated by Django 6.0.4 on 2026-04-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actajuntadirectiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perspectiva', models.CharField(choices=[('financiera', 'Financiera'), ('comercial', 'Comercial'), ('operativa', 'Operativa'), ('cliente', 'Cliente'), ('aprendizaje', 'Aprendizaje')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('definicion', models.TextField()),
                ('meta_anual', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('por_proyecto', 'Por Proyecto')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_obtenido', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicadorestrategico')),
            ],
        ),
    ]
