# Generated by Django 6.0.4 on 2026-04-24 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_indicadorestrategico_seguimientoindicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('enero', 'Enero'), ('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'Abril'), ('mayo', 'Mayo'), ('junio', 'Junio'), ('julio', 'Julio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('noviembre', 'Noviembre'), ('diciembre', 'Diciembre')], max_length=20)),
                ('anio', models.IntegerField(default=2026)),
                ('meta_facturacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('facturacion_real', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyectofacturacion')),
            ],
            options={
                'unique_together': {('mes', 'anio', 'proyecto')},
            },
        ),
    ]
