# Generated by Django 6.0.4 on 2026-04-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_proyectofacturacion_seguimientofacturacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('lugar_expedicion', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(default='Colombiano', max_length=50)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('nivel_academico', models.CharField(max_length=100)),
                ('profesion', models.CharField(blank=True, max_length=100)),
                ('habilidades', models.TextField(blank=True)),
                ('idiomas', models.CharField(default='Español', max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('fijo', 'Fijo'), ('indefinido', 'Indefinido'), ('obra', 'Obra o labor')], max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jornada', models.CharField(choices=[('diurna', 'Diurna'), ('nocturna', 'Nocturna')], max_length=20)),
                ('jefe', models.CharField(max_length=150)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DotacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_entrega', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
