# Generated by Django 6.0.4 on 2026-04-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empleado_dotacionempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaludEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(max_length=5)),
                ('eps', models.CharField(max_length=100)),
                ('pension', models.CharField(max_length=100)),
                ('cesantias', models.CharField(max_length=100)),
                ('arl', models.CharField(max_length=100)),
                ('alergias', models.TextField(blank=True)),
                ('contacto_emergencia', models.CharField(max_length=150)),
                ('telefono_emergencia', models.CharField(max_length=20)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
