# Generated by Django 6.0.4 on 2026-04-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_saludempleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='lugar_expedicion',
            new_name='ciudad_expedicion',
        ),
    ]
