# Generated by Django 6.0.4 on 2026-04-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_lugar_expedicion_empleado_ciudad_expedicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=200)),
                ('fecha_entrega', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('firma_empleado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
