# Generated by Django 6.0.4 on 2026-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_asignacionequipo_referencia_actaentregaequipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Baja')], default='disponible', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
