# Generated by Django 6.0.4 on 2026-04-30 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_inventarioequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionequipo',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='asignacionequipo',
            name='firma_empleado',
        ),
        migrations.RemoveField(
            model_name='asignacionequipo',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='asignacionequipo',
            name='serial',
        ),
        migrations.AddField(
            model_name='asignacionequipo',
            name='equipo_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventarioequipo'),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='fecha_compra',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipo',
            name='serial',
            field=models.CharField(max_length=100),
        ),
    ]
