# Generated by Django 6.0.4 on 2026-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_asignacionequipo_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='afp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='arl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cesantias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='empleado',
            name='eps',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='parentesco_emergencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
