# Generated by Django 6.0.4 on 2026-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_empleado_afp_empleado_arl_empleado_cesantias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='empleado',
            name='motivo_retiro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jornada',
            field=models.CharField(choices=[('diurna', 'Diurna'), ('nocturna', 'Nocturna'), ('mixta', 'Mixta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('indefinido', 'Indefinido'), ('obra', 'Obra o labor'), ('aprendizaje', 'Aprendizaje')], max_length=20),
        ),
    ]
