# Generated by Django 6.0.4 on 2026-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_empleado_alergias_empleado_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='afp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='arl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cesantias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='eps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='parentesco_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
