# Generated by Django 6.0.4 on 2026-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_documentoempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ciudad_residencia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
