# Generated by Django 6.0.4 on 2026-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_empleado_ciudad_residencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
