# Generated by Django 6.0.4 on 2026-06-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_empleado_fecha_finalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('periodo_desde', models.DateField()),
                ('periodo_hasta', models.DateField()),
                ('dias_solicitados', models.IntegerField()),
                ('vacaciones_desde', models.DateField()),
                ('vacaciones_hasta', models.DateField()),
                ('dias_disponibles', models.IntegerField(default=15)),
                ('nombre_rrhh', models.CharField(max_length=200)),
                ('jefe_inmediato', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
