# Generated by Django 6.0.4 on 2026-06-03 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_vacacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='dias_disponibles',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='vacacion',
            name='dias_pendientes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacacion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacacion',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
