# Generated by Django 6.0.4 on 2026-06-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_vacacion_dias_disponibles_vacacion_dias_pendientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacacion',
            name='dias_disponibles',
        ),
    ]
