# Generated by Django 6.0.4 on 2026-06-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_vacacion_dias_disponibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante_rrhh', models.CharField(default='Gestión RRHH', max_length=150)),
                ('testigo', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_hechos', models.DateField()),
                ('descripcion_falta', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
