# Generated by Django 6.0.4 on 2026-06-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_descargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='descargo',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descargo',
            name='observaciones_finales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
