# Generated by Django 6.0.4 on 2026-06-12 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_descargo_hora_cierre_descargo_observaciones_finales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitacionDescargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diligencia', models.DateField()),
                ('hora_diligencia', models.TimeField()),
                ('lugar_diligencia', models.CharField(default='Oficina de RRHH', max_length=150)),
                ('descripcion_hechos', models.TextField()),
                ('clausula_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('articulo_reglamento', models.CharField(blank=True, max_length=100, null=True)),
                ('norma_cst', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
