# Generated by Django 6.0.4 on 2026-06-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_citaciondescargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroCesantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_retiro', models.CharField(max_length=20)),
                ('fecha_solicitud', models.DateField()),
                ('fondo_cesantias', models.CharField(default='Protección', max_length=100)),
                ('valor_retiro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('direccion_vivienda', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_vivienda', models.TextField(blank=True, null=True)),
                ('institucion_educativa', models.CharField(blank=True, max_length=200, null=True)),
                ('programa_estudio', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiario', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_retiro_definitivo', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
