# Generated by Django 6.0.4 on 2026-06-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_retirocesantias'),
    ]

    operations = [
        migrations.CreateModel(
            name='InduccionCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_evento', models.CharField(choices=[('INDUCCION', 'Inducción'), ('REINDUCCION', 'Reinducción'), ('CAPACITACION', 'Capacitación específica')], max_length=20)),
                ('tema_capacitacion', models.CharField(blank=True, max_length=200, null=True)),
                ('facilitador', models.CharField(blank=True, max_length=150, null=True)),
                ('duracion_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
