# Generated by Django 6.0.4 on 2026-06-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_induccioncapacitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompromisoPagoDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion_dano', models.TextField()),
                ('fecha_evento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
