# Generated by Django 6.0.4 on 2026-07-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_compromisopagodano'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
    ]
