# Generated by Django 6.0.4 on 2026-07-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_suspensioncontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=50)),
                ('centro_formacion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=200)),
                ('numero_grupo', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio_lectiva', models.DateField()),
                ('fecha_fin_lectiva', models.DateField()),
                ('fecha_inicio_practica', models.DateField()),
                ('fecha_fin_practica', models.DateField()),
                ('porcentaje_apoyo', models.IntegerField(default=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institucionformacion')),
            ],
        ),
    ]
