# Generated by Django 6.0.4 on 2026-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_institucionformacion_contratoaprendizaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoaprendizaje',
            name='institucion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
