# Generated by Django 6.0.4 on 2026-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_contratoaprendizaje_institucion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitucionFormacion',
        ),
        migrations.AddField(
            model_name='contratoaprendizaje',
            name='centro_formacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contratoaprendizaje',
            name='nit_institucion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estrato',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
