# Generated by Django 6.0.4 on 2026-07-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_delete_institucionformacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='barrio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
