# Generated by Django 6.0.4 on 2026-07-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_empleado_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionDisciplinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_suspension', models.TextField()),
                ('fecha_falta', models.DateField()),
                ('articulos_infringidos', models.TextField()),
                ('fecha_inicio_suspension', models.DateField()),
                ('fecha_fin_suspension', models.DateField()),
                ('fecha_reincorporacion', models.DateField()),
                ('responsabilidad_pecuniaria', models.TextField(blank=True, null=True)),
                ('consecuencia_reincidencia', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones_disciplinarias', to='core.empleado')),
            ],
        ),
    ]
