# Generated by Django 6.0.4 on 2026-07-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_suspensiondisciplinaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dotacionempleado',
            options={'ordering': ['-fecha_entrega']},
        ),
        migrations.RemoveField(
            model_name='dotacionempleado',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='dotacionempleado',
            name='elemento',
        ),
        migrations.AddField(
            model_name='dotacionempleado',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dotacionempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotaciones', to='core.empleado'),
        ),
    ]
