# Generated by Django 6.0.4 on 2026-07-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_dotacionempleado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_emcali', models.CharField(max_length=50, unique=True, verbose_name='Número Proyecto EMCALI')),
                ('nombre', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=100)),
                ('circuito', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('Planeación', 'Planeación'), ('En ejecución', 'En ejecución'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Planeación', max_length=30)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
