# Generated by Django 6.0.4 on 2026-07-30 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apoyo', models.PositiveIntegerField(verbose_name='Número de apoyo')),
                ('nodo', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En ejecución', 'En ejecución'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=30)),
            ],
            options={
                'verbose_name': 'Apoyo',
                'verbose_name_plural': 'Apoyos',
                'ordering': ['numero_apoyo'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('unidad', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ApoyoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_instalada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad instalada')),
                ('apoyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='core.apoyo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apoyos', to='core.material')),
            ],
            options={
                'verbose_name': 'Material por Apoyo',
                'verbose_name_plural': 'Materiales por Apoyo',
            },
        ),
        migrations.CreateModel(
            name='PosteAPosteBajaTension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('aviso', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_apoyos_programados', models.PositiveIntegerField(default=0)),
                ('numero_apoyos_realizados', models.PositiveIntegerField(default=0)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_baja_tension', to='core.proyecto')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realizado_poste_baja_tension', to='core.empleado')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_poste_baja_tension', to='core.empleado')),
            ],
            options={
                'verbose_name': 'Poste a Poste Baja Tensión',
                'verbose_name_plural': 'Poste a Poste Baja Tensión',
            },
        ),
        migrations.AddField(
            model_name='apoyo',
            name='poste_a_poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apoyos', to='core.posteapostebajatension'),
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_materiales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
    ]
