# Generated by Django 6.0.4 on 2026-08-03 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_apoyo_material_apoyomaterial_posteapostebajatension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='circuito',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='numero_emcali',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número Proyecto'),
        ),
    ]
