# Generated by Django 6.0.4 on 2026-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_proyecto_circuito_remove_proyecto_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('BT', 'Baja Tensión'), ('AP', 'Alumbrado Público'), ('MT', 'Media Tensión')], default='AP', max_length=2),
            preserve_default=False,
        ),
    ]
