# Generated by Django 6.0.4 on 2026-08-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_proyecto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoyo',
            name='poste_a_poste',
        ),
        migrations.AddField(
            model_name='apoyo',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoyos', to='core.proyecto'),
        ),
        migrations.DeleteModel(
            name='PosteAPosteBajaTension',
        ),
    ]
