# Generated by Django 6.0.4 on 2026-08-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_apoyo_poste_a_poste_apoyo_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='apoyo',
            name='aislador',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='banda_cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='banda_diametro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='brazo_inst',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='cable_3x14',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='cable_6_alum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='cable_subterraneo_calibre',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='cable_subterraneo_metros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='cable_tpx',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='caja_nueva',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='caja_vieja',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='cimentacion_zb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='cimentacion_zd',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='cinta_bandit_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='codigo_lum_inst',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='conc_lum_gel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='conc_lum_perfo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='conc_lum_resor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='contramarco_si',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='coraza_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='excavacion_metros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='fotocelda_inst',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='grillete',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='hebilla_adicional',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='kit_tierra_spt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='kit_tierra_varilla',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='nombre_quien_ejecuta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='percha',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='potencia_instalada',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='soldadura_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='tapa_alfa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='tapa_conc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='tuberia_metros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='tuberia_pulgadas',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='apoyo',
            name='tuberia_tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En ejecución', 'En ejecución'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='nodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='numero_apoyo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apoyo',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
