# Generated by Django 6.0.4 on 2026-08-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_inventario_apoyo_aislador_apoyo_banda_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['codigo'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='material',
            name='activo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='core.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
