# Generated by Django 6.0.4 on 2026-08-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename_material_codigo_to_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='item',
        ),
    ]
