# Generated by Django 6.0.4 on 2026-08-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_inventario_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoMaterialProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(verbose_name='Fecha Reporte')),
                ('supervisor', models.CharField(blank=True, default='', max_length=150, verbose_name='Supervisor / Quien entrega')),
                ('numero_planilla', models.CharField(blank=True, default='', max_length=100, verbose_name='N° Planilla / Reporte')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_material', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Consumo de Material en Obra',
                'verbose_name_plural': 'Consumos de Material en Obra',
                'ordering': ['-fecha_reporte', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleConsumoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Utilizada')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.consumomaterialproyecto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_proyecto', to='core.material')),
            ],
            options={
                'verbose_name': 'Detalle Consumo Material',
                'verbose_name_plural': 'Detalles Consumo Material',
            },
        ),
        migrations.CreateModel(
            name='EntradaMaterialProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(blank=True, default='', max_length=150, verbose_name='Proveedor')),
                ('numero_remision', models.CharField(blank=True, default='', max_length=100, verbose_name='N° Remisión / Factura')),
                ('recibido_por', models.CharField(blank=True, default='', max_length=150, verbose_name='Recibido por')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_material', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Entrada de Material a Proyecto',
                'verbose_name_plural': 'Entradas de Material a Proyectos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntradaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_proyecto', to='core.material')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.entradamaterialproyecto')),
            ],
            options={
                'verbose_name': 'Detalle Entrada Material',
                'verbose_name_plural': 'Detalles Entrada Material',
            },
        ),
    ]
