# Generated by Django 6.0.4 on 2026-08-24 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_apoyo_aislador_remove_apoyo_banda_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoyoLuminaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=100)),
                ('apoyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luminarias', to='core.apoyo')),
            ],
            options={
                'verbose_name': 'Luminaria por Apoyo',
                'verbose_name_plural': 'Luminarias por Apoyo',
            },
        ),
    ]
