# Generated by Django 6.0.4 on 2026-08-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_apoyoluminaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoyo',
            name='nombre_quien_ejecuta',
        ),
        migrations.AddField(
            model_name='apoyo',
            name='quien_ejecuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apoyos_ejecutados', to='core.empleado'),
        ),
    ]
