# Generated by Django 6.0.4 on 2026-08-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_apoyo_nombre_quien_ejecuta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequeridoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_proyecto', to='core.material')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_requeridos', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Material Requerido por Proyecto',
                'verbose_name_plural': 'Materiales Requeridos por Proyecto',
                'unique_together': {('proyecto', 'material')},
            },
        ),
    ]
