# Generated by Django on 2026-09-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_materialrequeridoproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroMaterialProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(blank=True, default='', max_length=150, verbose_name='Responsable / Cuadrilla')),
                ('numero_acta', models.CharField(blank=True, default='', max_length=100, verbose_name='N° Acta / Planilla de Retiro')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros_material', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Retiro / Desmonte de Material',
                'verbose_name_plural': 'Retiros / Desmontes de Material',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRetiroMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Retirada')),
                ('estado_material', models.CharField(blank=True, choices=[('Bueno', 'Bueno / Reutilizable'), ('Chatarra', 'Chatarra / Dañado'), ('Inservible', 'Inservible')], default='Bueno', max_length=50, verbose_name='Estado del Material')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros_proyecto', to='core.material')),
                ('retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.retiromaterialproyecto')),
            ],
            options={
                'verbose_name': 'Detalle Retiro Material',
                'verbose_name_plural': 'Detalles Retiro Material',
            },
        ),
    ]
