# Generated by Django on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_retiromaterialproyecto_detalleretiromaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoyomaterial',
            name='cantidad_retirada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Retirada'),
        ),
        migrations.AlterField(
            model_name='apoyomaterial',
            name='cantidad_requerida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Instalada'),
        ),
    ]
