# Generated by Django 6.0.4 on 2026-09-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_apoyo_cantidad_retenida_apoyo_direccion_apoyo_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroproyecto',
            name='numero_maniobra_cointeca',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número Maniobra COINTECA'),
        ),
        migrations.AddField(
            model_name='macroproyecto',
            name='numero_maniobra_emcali',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número Maniobra EMCALI'),
        ),
    ]
