# Generated by Django 6.0.4 on 2026-09-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_macroproyecto_numero_maniobra_cointeca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Actividad')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción de la Actividad')),
                ('unidad', models.CharField(default='UN', max_length=20, verbose_name='Unidad de Medida')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Unitario ($)')),
                ('categoria', models.CharField(choices=[('Hincada y Aplomada', 'Hincada y Aplomada'), ('Redes y Cables', 'Redes y Cables'), ('Luminarias y Proyectores', 'Luminarias y Proyectores'), ('Transporte de Materiales', 'Transporte de Materiales'), ('Obra Civil y Excavación', 'Obra Civil y Excavación'), ('Herrajes y Accesorios', 'Herrajes y Accesorios'), ('Desmontes y Retiros', 'Desmontes y Retiros'), ('Otros Servicios', 'Otros Servicios')], default='Otros Servicios', max_length=50, verbose_name='Categoría')),
                ('tipo_calculo', models.CharField(choices=[('AUTOMATICO', 'Cálculo Automático por Fórmula'), ('MANUAL', 'Ingreso Manual en Terreno')], default='AUTOMATICO', max_length=20, verbose_name='Tipo de Cálculo')),
            ],
            options={
                'verbose_name': 'Ítem de Mano de Obra',
                'verbose_name_plural': 'Ítems de Mano de Obra',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ApoyoManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad Liquidada')),
                ('origen', models.CharField(choices=[('CALCULADO', 'Calculado Automáticamente'), ('MANUAL', 'Agregado / Modificado Manualmente')], default='CALCULADO', max_length=20)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('apoyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manos_obra', to='core.apoyo')),
                ('item_mano_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apoyos', to='core.itemmanoobra')),
            ],
            options={
                'verbose_name': 'Mano de Obra por Apoyo',
                'verbose_name_plural': 'Manos de Obra por Apoyo',
                'unique_together': {('apoyo', 'item_mano_obra')},
            },
        ),
    ]
