# Generated by Django 5.2.17 on 2026-09-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_actaentregaequipo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actajuntadirectiva',
            name='archivo_firmado',
            field=models.FileField(blank=True, null=True, upload_to='actas/firmadas/'),
        ),
        migrations.AddField(
            model_name='movimientocajamenor',
            name='categoria',
            field=models.CharField(choices=[('combustible', 'Combustible y Lubricantes'), ('viaticos', 'Viáticos y Alimentación'), ('ferreteria', 'Ferretería y Compras Menores'), ('peajes', 'Peajes y Transporte'), ('papeleria', 'Papelería y Trámites'), ('otros', 'Otros Gastos')], default='otros', max_length=30),
        ),
        migrations.AddField(
            model_name='movimientocajamenor',
            name='soporte',
            field=models.FileField(blank=True, null=True, upload_to='caja_menor/soportes/'),
        ),
    ]
