# Generated by Django 5.2.17 on 2026-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_actajuntadirectiva_archivo_firmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroproyecto',
            name='tipo',
            field=models.CharField(choices=[('AP', 'Alumbrado Público'), ('MT', 'Media Tensión')], default='AP', max_length=10, verbose_name='Tipo de Red'),
        ),
        migrations.AlterField(
            model_name='macroproyecto',
            name='numero_maniobra_cointeca',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número Maniobra / Proyecto COINTECA'),
        ),
        migrations.AlterField(
            model_name='macroproyecto',
            name='numero_maniobra_emcali',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número Maniobra / Proyecto EMCALI'),
        ),
    ]
