# Generated by Django 5.2.17 on 2026-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_macroproyecto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='numero_emcali',
            field=models.CharField(max_length=50, verbose_name='Número Proyecto'),
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('macroproyecto', 'numero_emcali'), name='unique_proyecto_por_macroproyecto'),
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(condition=models.Q(('macroproyecto__isnull', True)), fields=('numero_emcali',), name='unique_proyecto_sin_macroproyecto'),
        ),
    ]
