# Generated by Django 5.2.17 on 2026-10-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_proyecto_numero_emcali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='numero_cointeca',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número Maniobra / Proyecto COINTECA'),
        ),
    ]
