# Generated by Django 5.2.17 on 2026-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_proyecto_numero_cointeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoyomaterial',
            name='potencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Potencia (W)'),
        ),
    ]
