# Generated by Django 5.2.17 on 2026-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_apoyomaterial_potencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoyomaterial',
            name='codigo_luminaria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Luminaria'),
        ),
    ]
