# Generated by Django 5.2.17 on 2026-10-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_apoyomaterial_codigo_luminaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(default=2026, verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=10, verbose_name='Mes')),
                ('tipo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('QUINCENAL_1', 'Primera Quincena (1-15)'), ('QUINCENAL_2', 'Segunda Quincena (16-Fin)')], default='MENSUAL', max_length=20, verbose_name='Tipo de Período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('smmlv_base', models.DecimalField(decimal_places=2, default=1750905, max_digits=12, verbose_name='SMMLV Base')),
                ('auxilio_transporte_base', models.DecimalField(decimal_places=2, default=249095, max_digits=12, verbose_name='Auxilio de Transporte Base')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Devengado')),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Deducciones')),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Neto')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'ordering': ['-ano', '-mes', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNominaEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(blank=True, default='', max_length=30, verbose_name='Cédula / Documento')),
                ('cargo', models.CharField(blank=True, default='', max_length=150, verbose_name='Cargo')),
                ('salario_basico', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario Básico Mensual')),
                ('auxilio_transporte_pactado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Auxilio Transporte Pactado')),
                ('es_aprendiz_sena', models.BooleanField(default=False, verbose_name='Es Aprendiz SENA')),
                ('dias_laborados', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Días Laborados')),
                ('dias_incapacidad', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Días Incapacidad')),
                ('dias_no_remunerados', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Días No Remunerados')),
                ('basico_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Básico Devengado')),
                ('auxilio_transporte_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Auxilio Transporte Devengado')),
                ('horas_extras_recargos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Horas Extras y Recargos')),
                ('otros_devengados', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros Devengados / Bonos')),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Devengado')),
                ('deduccion_salud', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salud (4%)')),
                ('deduccion_pension', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pensión (4%)')),
                ('deduccion_afsp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fondo Solidaridad Pensional')),
                ('retencion_fuente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retención en la Fuente')),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otras Deducciones / Préstamos')),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Deducciones')),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto a Pagar')),
                ('observaciones', models.CharField(blank=True, default='', max_length=255, verbose_name='Novedades / Observaciones')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas', to='core.empleado', verbose_name='Empleado Vinculado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.periodonomina', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Detalle de Nómina',
                'verbose_name_plural': 'Detalles de Nómina',
                'ordering': ['id'],
            },
        ),
    ]
