from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from core.views import (
    inicio, 
    login_view, 
    dashboard, 
    caja_menor, 
    detalle_caja, 
    agregar_movimiento, 
    eliminar_movimiento, 
    editar_movimiento, 
    actas, 
    crear_acta, 
    detalle_acta, 
    editar_acta, 
    eliminar_acta, 
    indicadores, 
    crear_indicador, 
    detalle_indicador, 
    agregar_seguimiento, 
    eliminar_indicador, 
    editar_indicador, 
    editar_seguimiento, 
    eliminar_seguimiento, 
    facturacion, 
    crear_proyecto, 
    registrar_facturacion, 
    eliminar_facturacion, 
    editar_facturacion, 
    empleados, 
    rrhh,
    agregar_dotacion,
    crear_empleado,
    detalle_empleado,
    eliminar_empleado,
    certificacion_laboral,
    asignar_equipo,
    eliminar_equipo,
    editar_equipo,
    acta_entrega_equipos,
    inventario_equipos,
    crear_equipo_inventario,
    editar_equipo_inventario,
    eliminar_equipo_inventario,
    subir_documento,
    eliminar_documento,
    contrato_empleado,
    generar_contrato
) 

from django.contrib.auth.decorators import login_required
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio),
    path('login/', login_view, name='login'),
    path('dashboard/', dashboard, name='dashboard'),
    path('caja-menor/', caja_menor, name='caja_menor'),
    path('caja-menor/<int:id>/', detalle_caja, name='detalle_caja'),
    path('caja-menor/<int:id>/agregar/', agregar_movimiento, name='agregar_movimiento'),
    path('movimiento/<int:id>/eliminar/', eliminar_movimiento, name='eliminar_movimiento'),
    path('movimiento/<int:id>/editar/', editar_movimiento, name='editar_movimiento'),
    path('actas/', actas, name='actas'),
    path('actas/crear/', crear_acta, name='crear_acta'),
    path('actas/<int:id>/', detalle_acta, name='detalle_acta'),
    path('actas/<int:id>/editar/', editar_acta, name='editar_acta'),
    path('actas/<int:id>/eliminar/', eliminar_acta, name='eliminar_acta'),
    path('indicadores/', indicadores, name='indicadores'),
    path('indicadores/crear/', crear_indicador, name='crear_indicador'),
    path('indicadores/<int:id>/', detalle_indicador, name='detalle_indicador'),
    path('indicadores/<int:id>/agregar-seguimiento/', agregar_seguimiento, name='agregar_seguimiento'),
    path('indicadores/<int:id>/eliminar/', eliminar_indicador, name='eliminar_indicador'),
    path('indicadores/<int:id>/editar/', editar_indicador, name='editar_indicador'),
    path('seguimiento/<int:id>/editar/', editar_seguimiento, name='editar_seguimiento'),
    path('seguimiento/<int:id>/eliminar/', eliminar_seguimiento, name='eliminar_seguimiento'),
    path('indicadores/<int:id>/seguimiento/', agregar_seguimiento, name='agregar_seguimiento'),
    path('facturacion/', facturacion, name='facturacion'),
    path('facturacion/crear-proyecto/', crear_proyecto, name='crear_proyecto'),
    path('facturacion/registrar/', registrar_facturacion, name='registrar_facturacion'),
    path('facturacion/<int:id>/eliminar/', eliminar_facturacion, name='eliminar_facturacion'),
    path('facturacion/<int:id>/editar/', editar_facturacion, name='editar_facturacion'),
    path('rrhh/', rrhh, name='rrhh'),
    path('rrhh/empleados/', empleados, name='empleados'),
    path('rrhh/empleados/<int:id>/', detalle_empleado, name='detalle_empleado'),
    path('rrhh/empleados/<int:id>/dotacion/', agregar_dotacion, name='agregar_dotacion'),
    path('rrhh/empleados/crear/', crear_empleado, name='crear_empleado'),
    path('rrhh/empleados/<int:id>/eliminar/', eliminar_empleado, name='eliminar_empleado'),
    path('rrhh/empleados/<int:id>/certificacion/',certificacion_laboral,name='certificacion_laboral'),
    path('rrhh/empleados/<int:id>/asignar-equipo/', asignar_equipo, name='asignar_equipo'),
    path('rrhh/equipos/<int:id>/eliminar/', eliminar_equipo, name='eliminar_equipo'),
    path('rrhh/equipos/<int:id>/editar/', editar_equipo, name='editar_equipo'),
    path('rrhh/empleados/<int:id>/acta_equipos/', acta_entrega_equipos, name='acta_entrega_equipos'),
    path('rrhh/inventario/', inventario_equipos, name='inventario_equipos'),
    path('rrhh/inventario/crear/', crear_equipo_inventario, name='crear_equipo_inventario'),
    path('rrhh/inventario/<int:id>/editar/', editar_equipo_inventario, name='editar_equipo_inventario'),
    path('rrhh/inventario/<int:id>/eliminar/', eliminar_equipo_inventario, name='eliminar_equipo_inventario'),
    path('rrhh/empleados/<int:id>/subir-documento/', subir_documento, name='subir_documento'),
    path('rrhh/documentos/<int:id>/eliminar/', eliminar_documento, name='eliminar_documento'),
    path('rrhh/empleados/<int:id>/contrato/', generar_contrato, name='generar_contrato'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)